### ISSUE TITLE
Update building names that display on mouse hover to remove abbreviations

### ISSUE THREAD

**Issue by owenwells544** [Vacansee/app#14]
I want to have the full building names display when you hover over each building as opposed to just the abbreviation (ie DCC). This will make the site more accessible for people visiting the campus for the first time and using the tour feature.

**Comment by Acumane** [comment]
Agreed! In [a very old build](https://github.com/Vacansee/app/commit/02349e8eaffa6268f4ec36e29a1614340c44c45b), I used `<foreignObject>` tags to insert text right into the SVGs, which made transformations much simpler:
![bSvkEs](https://github.com/Vacansee/app/assets/94324138/98f9c5ea-21d0-458c-9821-d87bc6927381)

The idea was to have some sort of toggle-able titles and perhaps show other information at a glance.

**Comment by mattsweet417** [comment]
#19
