### ISSUE TITLE
Selected element on navbar needs to be more visible

### ISSUE THREAD

**Issue by AndersonCeci** [Vacansee/app#29]
[Screencast from 11.10.23 01:01:05.MD CEST.webm](https://github.com/Vacansee/app/assets/37506005/f9984217-cfbe-4e76-9a0d-9e3a33b36bf0)

I don't know if this is intentional, but it can be done better if you can assign me this issue I can help with it

**Comment by Acumane** [comment]
Duplicate #13
> Home and about buttons are just placeholders demoing Vue Routing. We should have a conversation about what kind of buttons/pages should be (e.g. settings page?)

@mattsweet417 had some thoughts on this in #28, and concepts can be found in #4

The two of you should collaborate if possible given the overlap. Also keep in mind [CRN search](https://github.com/Vacansee/app/tree/CRN-Search-Tab) will have an element in the navbar

**Comment by Acumane** [comment]
I'll keep this one open since you'll be assigned to it

**Comment by mattsweet417** [comment]
In #28 I am completely overhauling the nav bar, getting rid of the home and about links and relying on clickable icons. I also got rid of the about page entirely because the team thought it was redundant to the github and not needed.
