### ISSUE TITLE
weird white block

### ISSUE THREAD

**Issue by johnh03** [Vacansee/app#31]
On the newest branch of main, when you try to inspect the page the white building info block appears. Its the block that appears when you click on a building that is supposed to hold all the info of the building currently.

**Comment by johnh03** [comment]
Update on the issue, its not just inspecting, when you split the screen with the tab the info box also shows up, basically anything that doesn't full screen the map will cause the block to show up

**Comment by Acumane** [comment]
Can you screenshot what you're seeing? There's an edge case in portrait mode where the popup lingers, but this is caused by floor plans not existing yet (also cause of #12)

**Comment by johnh03** [comment]
<img width="596" alt="Vacansee - Google Chrome 10_13_2023 5_36_36 PM" src="https://github.com/Vacansee/app/assets/144492627/64bd61f9-16d7-4130-a327-9968611e4192">
