### ISSUE TITLE
Some buildings don't show correct pop up view and do not support floor plan additions

### ISSUE THREAD

**Issue by mattsweet417** [Vacansee/app#32]
When clicking on some buildings such as Academy Hall, EMPAC, VCC, etc. the pop up view shows up but there is no building name or sample picture. Additionally, you are unable to add building floorplans to those buildings.

**Comment by Acumane** [comment]
Errors were handled in [39599e3](https://github.com/Vacansee/app/commit/39599e3d1ff1045d53c56ce16a819f4a4182412e)

These rooms are special because they host no classes (according to SIS), so they never make it on to the `rooms.json`, unfortunately.
