### ISSUE TITLE
Global reactive variables

### ISSUE THREAD

**Issue by Acumane** [Vacansee/app#9]
To minimize duplication of efforts, track states used by many components in a single global variable.

Here's our current global reactive object in `main.js`. Any changes to its members will trigger reactivity in components that reference it:

```js
const global = reactive({ 
	data: data,
	loading: isFetching,
	error: error,
	bldg: '',
	room: '',
	floor: '1',
	time: Moment.tz('America/New_York').format('e:HHmm'),
	firstCalc: false,
})
```
A good candidate: several components are currently tracking aspect ratio independently. This logic should be consolidated and added to the global reactive object.

**Comment by Acumane** [comment]
Where sensible, should also convert components using props to inherit properties over to the global reactive object

**Comment by BoundlessFate** [comment]
will work on this changing aspect ratio to a global reactive variable here and tie it into my work on issue #10
